repos:
  - repo: https://github.com/rgraue/pre-commit-mirror-checkstyle
    rev: v0.1.15
    hooks:
      - id: checkstyle-java
        args: ["-c", "google"]
        files: \.java$
        always_run: true

  - repo: local
    hooks:
      - id: pmd-maven
        name: PMD via Maven
        entry: mvn org.apache.maven.plugins:maven-pmd-plugin:3.21.2:check
        language: maven
        types: [java]
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: spotbugs-maven
        name: SpotBugs via Maven
        entry: mvn com.github.spotbugs:spotbugs-maven-plugin:4.8.5.0:check
        language: maven
        types: [java]
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: jdepend-maven
        name: JDepend via Maven
        entry: mvn org.codehaus.mojo:jdepend-maven-plugin:2.1:generate
        language: maven
        types: [java]
        pass_filenames: false
        always_run: true
