repos:
  - repo: local
    hooks:
      - id: checkstyle
        name: Checkstyle Java
        entry: mvn com.puppycrawl.tools:checkstyle:checkstyle
        language: system
        types: [java]
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: pmd-maven
        name: PMD via Maven
        entry: mvn org.apache.maven.plugins:maven-pmd-plugin:3.21.2:check
        language: system
        types: [java]
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: spotbugs-maven
        name: SpotBugs via Maven
        entry: mvn com.github.spotbugs:spotbugs-maven-plugin:4.8.5.0:check
        language: system
        types: [java]
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: jdepend-maven
        name: JDepend via Maven
        entry: mvn org.codehaus.mojo:jdepend-maven-plugin:2.1:generate
        language: system
        types: [java]
        pass_filenames: false
        always_run: true

